apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-local-volume-prep.fullname" . }}
  labels:
    {{- include "aws-local-volume-prep.labels" . | nindent 4 }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-local-volume-prep.fullname" . }}
  labels:
    {{- include "aws-local-volume-prep.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-local-volume-prep.fullname" . }}
  labels:
    {{- include "aws-local-volume-prep.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aws-local-volume-prep.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-local-volume-prep.fullname" . }}
    namespace: {{ .Release.Namespace }}
