replicaCount: 1

image:
  repository: shopstic/jdk11-sbt
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

fdbClusterFileConfigMapName:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
