apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbt.fullname" . }}
  labels:
    {{- include "sbt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sbt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sbt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "trap : TERM INT HUP; sleep infinity & wait"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /builds
              name: builds
            {{- if .Values.fdbClusterFileConfigMapName }}
            - name: fdb-cluster-file
              mountPath: /root/.fdb/cluster.file
              subPath: cluster.file
             {{- end }}
      volumes:
        - name: builds
          hostPath:
            path: /builds
        {{- if .Values.fdbClusterFileConfigMapName }}
        - name: fdb-cluster-file
          configMap:
            name: {{ .Values.fdbClusterFileConfigMapName }}
            items:
              - key: clusterFile
                path: cluster.file
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
