{{- $serviceAccount := (include "kind-builder.serviceAccountName" .) -}}
{{- $labels := (include "kind-builder.labels" .) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- $labels | nindent 4 }}
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccount }}
  labels:
    {{- $labels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceAccount }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccount }}
    namespace: {{ .Release.Namespace }}
