---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kind-builder.fullname" . }}
  labels:
    {{- include "kind-builder.labels" . | nindent 4 }}
data:
  iacGitlabRepoArchiveUrl: {{ .Values.iacGitlabRepo.archiveUrl | b64enc }}
  iacGitlabRepoPrivateToken: {{ .Values.iacGitlabRepo.privateToken | b64enc }}
