version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: shopstic/docker-builder:0.0.2
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Reconcile
          command: |
            ./cli reconcile 1
