apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ipmi-exporter.fullname" . }}
  labels:
    {{- include "ipmi-exporter.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "ipmi-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      honorLabels: true
      path: /metrics
      scheme: http
      interval: 5s
      scrapeTimeout: 5s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
        - regex: '^pod$'
          action: labeldrop
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: '^ipmi_.+'
          action: keep
