FROM centos:centos7

RUN \
  yum update -y && \
  yum install -y which && \
  yum clean all

WORKDIR /app
RUN \
  groupadd -r -g 1001 foundationdb && \
  useradd -r -s /bin/false -u 1001 -g 1001 foundationdb && \
  chown -R foundationdb:foundationdb /app

ARG PACKAGE_VERSION

RUN \
  mkdir /tmp/fdb && \
  cd /tmp/fdb && \
  curl -Lo fdb-clients.rpm https://www.foundationdb.org/downloads/$PACKAGE_VERSION/rhel7/installers/foundationdb-clients-$PACKAGE_VERSION-1.el7.x86_64.rpm && \
  curl -Lo fdb-server.rpm https://www.foundationdb.org/downloads/$PACKAGE_VERSION/rhel7/installers/foundationdb-server-$PACKAGE_VERSION-1.el7.x86_64.rpm && \
  rpm -iv /tmp/fdb/fdb-clients.rpm && \
  rpm -iv /tmp/fdb/fdb-server.rpm && \
  rm -Rf /tmp/fdb

RUN \
  curl -Lo /usr/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 && \
  chmod +x /usr/bin/dumb-init

USER foundationdb:foundationdb

COPY ./entrypoint.sh /app/entrypoint.sh
COPY ./base.conf /app/base.conf