---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-runner-kind.fullname" . }}
  labels:
    {{- include "gitlab-runner-kind.labels" . | nindent 4 }}
data:
  gitlabRunnerRegisterRegistrationToken: {{ .Values.gitlabRunner.register.registrationToken | b64enc }}
